{
 "title": "EigenDA",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Eigen DA statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average dispatch latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(server_da_dispatcher_blob_dispatch_latency_seconds_sum{}[$__rate_interval]))/sum(rate(server_da_dispatcher_blob_dispatch_latency_seconds_count{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average inclusion latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(server_da_dispatcher_inclusion_latency_sum{}[$__rate_interval]))/sum(rate(server_da_dispatcher_inclusion_latency_count{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average blob size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(server_da_dispatcher_blob_size_bytes_sum{}[$__rate_interval])) \n/\nsum(rate(server_da_dispatcher_blob_size_bytes_count{}[$__rate_interval]))\n",
     "legendFormat": "Avg blob size"
    }
   ]
  },
  {
   "title": "Dispatched & Included blobs",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "server_da_dispatcher_last_dispatched_l1_batch{}",
     "legendFormat": "included blobs"
    },
    {
     "expr": "server_da_dispatcher_last_included_l1_batch{}",
     "legendFormat": "dispatched blobs"
    }
   ]
  }
 ]
}