{
 "title": "zksync-os-server",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(process_started_at,namespace)"
    }
   },
   { "name": "component", "query": { "query": "label_values(component)" } },
   {
    "name": "pod",
    "query": {
     "query": "label_values(component_time_spent_in_state{namespace=\"$namespace\"},pod)"
    }
   },
   { "name": "l1_operations", "query": "commit,prove,execute" },
   {
    "name": "rpc_methods",
    "query": {
     "query": "label_values(response_time_seconds_count,method)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General - all pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by (pod) ((execution_block_number{namespace=~\"$namespace|\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Batch Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "max by (stage) (batcher_batch_number{namespace=~\"$namespace|\", stage!=\"fri_proved_fake\"})",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Watchdog Status",
   "type": "state-timeline",
   "description": "deposit - L1->L2 token deposit performed with interval;\ndepositUser - observed L1->L2 deposits (checks if last deposit was executed on L2), reflects also status of watchdog own deposits if they are last;\ntransfer - simple 1 wei L2 base token transfer",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "min by(flow)(watchdog_status{flow=~\".*\", namespace=~\"$namespace|\"})",
     "legendFormat": "{{flow}}"
    }
   ]
  },
  {
   "title": "Suspended Flux Releases",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "max by (exported_namespace, name,) (flux_resource_info{suspended=\"True\", kind=\"HelmRelease\", exported_namespace=~\"prover|$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - process_started_at{namespace=~\"$namespace|\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n    sum(kube_pod_container_status_waiting_reason{namespace=~\"$namespace|\"}) by (pod, reason)\n    ,\n    \"role\",\"$1\",\"reason\",\"(.+)\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L1 contracts",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "max by (namespace, bridgehub, diamond_proxy, validator_timelock) (l1_state_l1_contract_addresses{namespace=~\"$namespace|\"})",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "L1 operators",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "(l1_sender_l1_operator_address{namespace=~\"$namespace|\"})",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "5m rolling SLIs",
   "type": "timeseries",
   "description": "SLIs (percentage of successful probes) over the last 5 minutes",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum(rate(watchdog_status_hist_bucket{le=\"1\",namespace=~\"$namespace|\",flow=\"block_number\"}[5m])) - sum(rate(watchdog_status_hist_bucket{le=\"0.01\",namespace=~\"$namespace|\",flow=\"block_number\"}[5m])))\n  / sum(rate(watchdog_status_hist_count{namespace=~\"$namespace|\",flow=\"block_number\"}[5m]))",
     "legendFormat": "API SLI"
    },
    {
     "expr": "100 * (sum(rate(watchdog_status_hist_bucket{le=\"1\",namespace=~\"$namespace|\",flow=\"transfer\"}[5m])) - sum(rate(watchdog_status_hist_bucket{le=\"0.01\",namespace=~\"$namespace|\",flow=\"transfer\"}[5m])))\n  / sum(rate(watchdog_status_hist_count{namespace=~\"$namespace|\",flow=\"transfer\"}[5m]))",
     "legendFormat": "Sequencer SLI"
    }
   ]
  },
  {
   "title": "SLIs Monthly",
   "type": "stat",
   "description": "SLIs (percentage of successful probes) over the last 30 days",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(rate(watchdog_status_hist_bucket{le=\"1\",namespace=~\"$namespace|\",flow=\"block_number\"}[30d])) - sum(rate(watchdog_status_hist_bucket{le=\"0.01\",namespace=~\"$namespace|\",flow=\"block_number\"}[30d])))\n  / sum(rate(watchdog_status_hist_count{namespace=~\"$namespace|\",flow=\"block_number\"}[30d]))",
     "legendFormat": "API SLI"
    },
    {
     "expr": "100 * (sum(rate(watchdog_status_hist_bucket{le=\"1\",namespace=~\"$namespace|\",flow=\"transfer\"}[30d])) - sum(rate(watchdog_status_hist_bucket{le=\"0.01\",namespace=~\"$namespace|\",flow=\"transfer\"}[30d])))\n  / sum(rate(watchdog_status_hist_count{namespace=~\"$namespace|\",flow=\"transfer\"}[30d]))",
     "legendFormat": "Sequencer SLI"
    }
   ]
  },
  {
   "title": "Block seal reason (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "sum by (seal_reason) (rate(execution_seal_reason{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]))",
     "legendFormat": "{{seal_reason}}"
    }
   ]
  },
  {
   "title": "Batch seal reason ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (seal_reason) (increase(batcher_seal_reason{namespace=~\"$namespace|\"}[$__interval]))",
     "legendFormat": "{{seal_reason}}"
    }
   ]
  },
  {
   "title": "FRI Proving time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (type, id) (rate(prover_prove_time_seconds_sum{stage=\"fri\", namespace=~\"$namespace|\"}[$__rate_interval]) / rate(prover_prove_time_seconds_count{stage=\"fri\", namespace=~\"$namespace|\"}[$__rate_interval]))",
     "legendFormat": "{{type}}-{{id}}"
    }
   ]
  },
  {
   "title": "Watchdog Inclusion time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "watchdog_latency{namespace=\"$namespace\", flow=\"transfer\"}",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Component States",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by (component, generic_state) (irate(component_time_spent_in_state{namespace=~\"$namespace|\", pod=~\"$pod|\", component!=\"batcher\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "FRI Proving time per L2 tx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (type, id) (rate(prover_prove_time_per_tx_seconds_sum{stage=\"fri\", namespace=~\"$namespace|\"}[$__rate_interval]) / rate(prover_prove_time_per_tx_seconds_count{stage=\"fri\", namespace=~\"$namespace|\"}[$__rate_interval]))",
     "legendFormat": "{{type}}-{{id}}"
    }
   ]
  },
  {
   "title": "General info",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "max by (namespace, fee_collector_address) (fee_collector_address{namespace=~\"$namespace|\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (namespace) (chain_id{namespace=~\"$namespace|\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "General - $pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block Number",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "batcher_block_number{namespace=~\"$namespace|\", pod=~\"$pod|\"}",
       "legendFormat": "{{stage}}"
      },
      {
       "expr": "max(execution_block_number{namespace=~\"$namespace|\", pod=~\"$pod|\"})",
       "legendFormat": "block_sealed"
      }
     ]
    },
    {
     "title": "Sequencer Transactions per Hour",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 38 },
     "targets": [
      {
       "expr": "max (rate(execution_executed_transactions{namespace=~\"$namespace\", pod=~\"$pod\"}[5m]) * 3600)\n",
       "legendFormat": "Transactions per Hour"
      }
     ]
    },
    {
     "title": "FRI proofs per hour",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "sum by (type) (rate(prover_prove_time_seconds_count{stage=\"fri\", namespace=~\"$namespace|\"}[5m]) * 3600)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Prover Input Generation",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 38 },
     "targets": [
      {
       "expr": "rate(prover_input_generator_prover_input_generation_seconds_bucket{namespace=~\"$namespace|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sequencer TPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 851 },
     "targets": [
      {
       "expr": "max by (command) (irate(execution_executed_transactions{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sequencer gas per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 851 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(execution_transaction_gas_used_sum[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Operator balance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 867 },
     "fieldConfig": { "defaults": { "unit": "ETH" } },
     "targets": [
      {
       "expr": "min by (command) (l1_sender_balance{namespace=~\"$namespace|\"})",
       "legendFormat": "{{command}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Block Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 99 },
     "targets": [
      {
       "expr": "irate(sum(execution_seal_reason{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transactions per Block",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 99 },
     "targets": [
      {
       "expr": "rate(execution_transactions_per_block_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Gas per Block",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(execution_gas_per_block_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]) / rate(execution_gas_per_block_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Gas per Block",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 99 },
     "targets": [
      {
       "expr": "rate(execution_gas_per_block_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transactions per Block",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 755 },
     "targets": [
      {
       "expr": "rate(execution_transactions_per_block_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]) / rate(execution_transactions_per_block_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Native per Block",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 755 },
     "targets": [
      {
       "expr": "rate(execution_computational_native_used_per_block_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pubdata per Block",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 755 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(execution_pubdata_per_block_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]) / rate(execution_pubdata_per_block_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Pubdata per Block",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 755 },
     "targets": [
      {
       "expr": "rate(execution_pubdata_per_block_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Native per Block",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 763 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(execution_computational_native_used_per_block_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]) / rate(execution_computational_native_used_per_block_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "average"
      }
     ]
    }
   ]
  },
  {
   "title": "Batch Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transactions per batch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 930 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(batcher_transactions_per_batch_sum{namespace=~\"$namespace|\"}[$__rate_interval]) / irate(batcher_transactions_per_batch_count{namespace=~\"$namespace|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Blocks per batch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 930 },
     "targets": [
      {
       "expr": "irate(batcher_blocks_per_batch_sum{namespace=~\"$namespace|\"}[$__rate_interval]) / irate(batcher_blocks_per_batch_count{namespace=~\"$namespace|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Native per Batch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 10, "y": 930 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(batcher_computational_native_used_per_batch_sum{namespace=~\"$namespace|\"}[$__rate_interval]) / rate(batcher_computational_native_used_per_batch_count{namespace=~\"$namespace|\"}[$__rate_interval])",
       "legendFormat": "average"
      }
     ]
    }
   ]
  },
  {
   "title": "Mempool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inserted transactions",
     "type": "timeseries",
     "description": "Tracks the number of transactions per second that are inserted and removed from the transaction pool, as well as the number of invalid transactions per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(sum(transaction_pool_inserted_transactions{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]))",
       "legendFormat": "Inserted transactions"
      },
      {
       "expr": "rate(sum(transaction_pool_invalid_transactions{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]))",
       "legendFormat": "Invalid transactions"
      },
      {
       "expr": "rate(sum(transaction_pool_removed_transactions{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]))",
       "legendFormat": "Removed transactions"
      }
     ]
    },
    {
     "title": "Subpool transaction count",
     "type": "timeseries",
     "description": "Tracks the number of transactions in the various transaction pool sub-pools",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "expr": "sum(transaction_pool_basefee_pool_transactions{namespace=~\"$namespace|\", pod=~\"$pod|\"})",
       "legendFormat": "Base fee pool transactions"
      },
      {
       "expr": "sum(transaction_pool_pending_pool_transactions{namespace=~\"$namespace|\", pod=~\"$pod|\"})",
       "legendFormat": "Pending pool transactions"
      },
      {
       "expr": "sum(transaction_pool_queued_pool_transactions{namespace=~\"$namespace|\", pod=~\"$pod|\"})",
       "legendFormat": "Queued pool transactions"
      },
      {
       "expr": "sum(transaction_pool_blob_pool_transactions{namespace=~\"$namespace|\", pod=~\"$pod|\"})",
       "legendFormat": "Blob pool transactions"
      }
     ]
    }
   ]
  },
  {
   "title": "L1 sender - $l1_operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "repeat": "l1_operations",
   "collapsed": true,
   "panels": [
    {
     "title": "Operator balance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "ETH" } },
     "targets": [
      {
       "expr": "min by (command) (l1_sender_balance{namespace=~\"$namespace|\", command=\"$l1_operations\"})",
       "legendFormat": "{{command}}"
      }
     ]
    },
    {
     "title": "$l1_operations Sender states",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 7, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (specific_state) (increase(component_time_spent_in_state{namespace=~\"$namespace|\", pod=~\"$pod|\", component=\"$l1_operations\"}[$__interval]))",
       "legendFormat": "{{specific_state}}"
      }
     ]
    },
    {
     "title": "$l1_operations L1 transactions in parallel",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_sender_parallel_transactions{namespace=~\"$namespace|\", command=\"$l1_operations\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$l1_operations L1 transaction fee",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "ETH" } },
     "targets": [
      {
       "expr": "irate(l1_sender_l1_transaction_fee_ether_sum{namespace=~\"$namespace|\", command=\"$l1_operations\"}[$__rate_interval]) / irate(l1_sender_l1_transaction_fee_ether_count{namespace=~\"$namespace|\", command=\"$l1_operations\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$l1_operations L1 transaction fee per l2 tx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "ETH" } },
     "targets": [
      {
       "expr": "irate(l1_sender_l1_transaction_fee_per_l2_tx_ether_sum{namespace=~\"$namespace|\", command=\"$l1_operations\"}[$__rate_interval]) / irate(l1_sender_l1_transaction_fee_per_l2_tx_ether_count{namespace=~\"$namespace|\", command=\"$l1_operations\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$l1_operations L1 transactions gas used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(l1_sender_gas_used_sum{namespace=~\"$namespace|\", command=\"$l1_operations\"}[$__rate_interval]) / irate(l1_sender_gas_used_count{namespace=~\"$namespace|\", command=\"$l1_operations\"}[$__rate_interval])",
       "legendFormat": "Gas used"
      }
     ]
    },
    {
     "title": "$l1_operations L1 transactions gas used per L2 tx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(l1_sender_gas_used_per_l2_tx_sum{namespace=~\"$namespace|\", command=\"$l1_operations\"}[$__rate_interval]) / irate(l1_sender_gas_used_per_l2_tx_count{namespace=~\"$namespace|\", command=\"$l1_operations\"}[$__rate_interval])",
       "legendFormat": "Gas used"
      }
     ]
    }
   ]
  },
  {
   "title": "All Component States",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "$component State Distribution",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 210 },
     "repeat": "component",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (specific_state) (irate(component_time_spent_in_state{namespace=~\"$namespace|\", pod=~\"$pod|\", component=\"$component\"}[$__rate_interval]))",
       "legendFormat": "{{specific_state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Batcher Subsystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Batch Latency by Stage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 256 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (stage) (increase(batcher_execution_stages_seconds_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__interval]))",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Batch Number",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 256 },
     "targets": [
      {
       "expr": "batcher_batch_number{namespace=~\"$stage|\"}",
       "legendFormat": "{{stage}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Execution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sequencer State Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 221 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (specific_state) (irate(component_time_spent_in_state{namespace=~\"$namespace|\", pod=~\"$pod|\", component=\"sequencer\"}[$__rate_interval]))",
       "legendFormat": "{{specific_state}}"
      }
     ]
    },
    {
     "title": "one tx (vm+storage) exec time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 221 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (measure) (irate(execution_tx_execution_seconds_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]) / irate(execution_tx_execution_seconds_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]))",
       "legendFormat": "{{measure}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Proving",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Proving time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1002 },
     "targets": [
      {
       "expr": "rate(prover_prove_time_seconds_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Tree",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "average block processing time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1003 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(tree_block_time_seconds_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]) / rate(tree_block_time_seconds_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "block processing in tree",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1003 },
     "targets": [
      {
       "expr": "rate(tree_block_time_seconds_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "average entry processing time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1011 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(tree_entry_time_seconds_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]) / rate(tree_entry_time_seconds_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "entry processing time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1011 },
     "targets": [
      {
       "expr": "rate(tree_entry_time_seconds_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tree Range size ",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1019 },
     "targets": [
      {
       "expr": "rate(tree_processing_range_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Block Replay Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13843 },
     "targets": [
      {
       "expr": "rate(block_replay_storage_get_latency_seconds_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response time",
     "type": "heatmap",
     "description": "JSON RPC API response time for all methods",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11860 },
     "targets": [
      {
       "expr": "sum(rate(response_time_seconds_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\"})[$__rate_interval]) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Response size",
     "type": "heatmap",
     "description": "JSON RPC API response size for all methods",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11860 },
     "targets": [
      {
       "expr": "sum(rate(response_size_bytes_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\"})[$__rate_interval]) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11868 },
     "targets": [
      {
       "expr": "sum(rate(response_time_seconds_count{namespace=~\"$namespace|\"}[$__rate_interval])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPS by method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11868 },
     "targets": [
      {
       "expr": "sum(rate(response_time_seconds_count{namespace=~\"$namespace|\"}[$__rate_interval])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "API response time by method",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Time ($rpc_methods)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13829 },
     "repeat": "rpc_methods",
     "targets": [
      {
       "expr": "sum(rate(response_time_seconds_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\", method=\"$rpc_methods\"})[$__rate_interval]) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API response size by method",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response size ($rpc_methods)",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15704 },
     "repeat": "rpc_methods",
     "targets": [
      {
       "expr": "sum(rate(response_size_bytes_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\", method=\"$rpc_methods\"})[$__rate_interval]) by (le)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Preimages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Preimage get",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19592 },
     "targets": [
      {
       "expr": "rate(preimages_get_seconds_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\", stage=\"total\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Preimage set",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19592 },
     "targets": [
      {
       "expr": "rate(preimages_set_seconds_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\", stage=\"total\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Preimage get avvg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19600 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(preimages_get_seconds_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]) / rate(preimages_get_seconds_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Preimage set avvg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19600 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(preimages_set_seconds_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]) / rate(preimages_set_seconds_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Preimage get count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19608 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(preimages_get_seconds_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "🚧 State persistence",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compact latency per block - avg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20630 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(storage_map_rocks_db_compact_seconds_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]) / rate(storage_map_rocks_db_compact_seconds_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Compact latency per block",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20630 },
     "targets": [
      {
       "expr": "rate(storage_map_rocks_db_compact_seconds_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "One block state persist ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20662 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(storage_add_diff_seconds_sum{namespace=~\"$namespace|\", pod=~\"$pod|\", stage=\"total\"}[$__rate_interval]) / rate(storage_add_diff_seconds_count{namespace=~\"$namespace|\", pod=~\"$pod|\", stage=\"total\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "storage access total avg time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20428 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(storage_view_access_seconds_sum{namespace=~\"$namespace|\", pod=~\"$pod|\", stage=\"total\"}[$__rate_interval]) / rate(storage_view_access_seconds_count{namespace=~\"$namespace|\", pod=~\"$pod|\", stage=\"total\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Storage access - diffs vs base",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20428 },
     "targets": [
      {
       "expr": "rate(storage_view_access_seconds_count{namespace=~\"$namespace|\", pod=~\"$pod|\", stage=\"base\"}[$__rate_interval])",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(storage_view_access_seconds_count{namespace=~\"$namespace|\", pod=~\"$pod|\", stage=\"total\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Storage Access time - total",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 20436 },
     "targets": [
      {
       "expr": "rate(storage_view_access_seconds_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\", stage=\"total\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Storage Access time - base",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 7, "x": 9, "y": 20436 },
     "targets": [
      {
       "expr": "rate(storage_view_access_seconds_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\", stage=\"base\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Storage Access time - diffs",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20436 },
     "targets": [
      {
       "expr": "rate(storage_access_latency_seconds_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\", stage=\"diff\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Storage Access - diffs scanned",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20444 },
     "targets": [
      {
       "expr": "rate(storage_view_diffs_scanned_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Storage Access - diffs scanned",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20444 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(storage_view_diffs_scanned_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]) / rate(storage_view_diffs_scanned_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Repository Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block insert latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21461 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(repositories_insert_block_seconds_sum{namespace=~\"$namespace|\", pod=~\"$pod|\", stage=\"total\"}[$__rate_interval])/rate(repositories_insert_block_seconds_count{namespace=~\"$namespace|\", pod=~\"$pod|\", stage=\"total\"}[$__rate_interval])",
       "legendFormat": "total"
      },
      {
       "expr": "rate(repositories_insert_block_seconds_sum{namespace=~\"$namespace|\", pod=~\"$pod|\", stage=\"account_properties\"}[$__rate_interval])/rate(repositories_insert_block_seconds_count{namespace=~\"$namespace|\", pod=~\"$pod|\", stage=\"account_properties\"}[$__rate_interval])",
       "legendFormat": "account properties"
      },
      {
       "expr": "rate(repositories_insert_block_seconds_sum{namespace=~\"$namespace|\", pod=~\"$pod|\", stage=\"block_receipts\"}[$__rate_interval])/rate(repositories_insert_block_seconds_count{namespace=~\"$namespace|\", pod=~\"$pod|\", stage=\"block_receipts\"}[$__rate_interval])",
       "legendFormat": "block receipts"
      },
      {
       "expr": "rate(repositories_insert_block_seconds_sum{namespace=~\"$namespace|\", pod=~\"$pod|\", stage=\"bytecodes\"}[$__rate_interval])/rate(repositories_insert_block_seconds_count{namespace=~\"$namespace|\", pod=~\"$pod|\", stage=\"bytecodes\"}[$__rate_interval])",
       "legendFormat": "bytecodes"
      }
     ]
    },
    {
     "title": "Block insert latency - total",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21461 },
     "targets": [
      {
       "expr": "rate(repositories_insert_block_seconds_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\", stage=\"total\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block insert latency per tx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21469 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(repositories_insert_block_per_tx_seconds_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])/rate(repositories_insert_block_per_tx_seconds_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block insert latency per tx",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21469 },
     "targets": [
      {
       "expr": "rate(repositories_insert_block_per_tx_seconds_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block persist latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21477 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(repositories_persist_block_seconds_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])/rate(repositories_persist_block_seconds_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block persist latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21477 },
     "targets": [
      {
       "expr": "rate(repositories_persist_block_seconds_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block persist latency per tx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21485 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(repositories_persist_block_per_tx_seconds_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])/rate(repositories_persist_block_per_tx_seconds_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block persist latency per tx",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21485 },
     "targets": [
      {
       "expr": "rate(repositories_persist_block_per_tx_seconds_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block data size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21493 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(repositories_block_data_size_bytes_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])/rate(repositories_block_data_size_bytes_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block data size per tx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21493 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(repositories_block_data_size_per_tx_bytes_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])/rate(repositories_block_data_size_per_tx_bytes_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Persistence lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21501 },
     "targets": [
      {
       "expr": "repositories_persistence_lag{namespace=~\"$namespace|\", pod=~\"$pod|\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}