{
 "title": "zksync-os-prover",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(snark_prover_latest_proven_block,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last proven block",
   "type": "timeseries",
   "description": "Last block that was successfully proven",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(snark_prover_latest_proven_block{namespace=~\"$namespace|\"})",
     "legendFormat": "SNARK"
    },
    {
     "expr": "max(fri_prover_latest_proven_block{namespace=~\"$namespace|\"})",
     "legendFormat": "FRI"
    }
   ]
  },
  { "title": "Snark", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Full proof generation time",
   "type": "heatmap",
   "description": "Amount of time taken for the whole proof generation(including intermediate steps)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (le) (rate(snark_prover_time_taken_full_seconds_bucket{namespace=~\"$namespace|\"})[30m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SNARK generation time",
   "type": "heatmap",
   "description": "Amount of time taken for the SNARK proof generation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(snark_prover_time_taken_snark_seconds_bucket{namespace=~\"$namespace|\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Final proof generation time",
   "type": "heatmap",
   "description": "Amount of time taken for the final proof generation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(snark_prover_time_taken_final_proof_seconds_bucket{namespace=~\"$namespace|\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fri proofs merged",
   "type": "timeseries",
   "description": "Amount of merged fri proofs(per one iteration)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum(snark_prover_fri_proofs_merged{namespace=~\"$namespace|\"})",
     "legendFormat": "FRI proof amount"
    }
   ]
  },
  {
   "title": "Merging fri proofs time",
   "type": "heatmap",
   "description": "Amount of time taken to merge fri proofs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(snark_prover_time_taken_merge_fri_seconds_bucket{namespace=~\"$namespace|\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Startup time over last 7 days(in seconds)",
   "type": "bargauge",
   "description": "How much time does it took to start a SNARK machine over last 7 days. The bucket values lay in means that it took from \"previous bucket\" seconds to \"current bucket\" seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(snark_prover_time_taken_startup_seconds_bucket{namespace=~\"$namespace|\"}[7d])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Fri Prover", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Time taken",
   "type": "heatmap",
   "description": "Time taken to generate a single FRI proof",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(fri_prover_time_taken_seconds_bucket{namespace=~\"$namespace|\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Request time(pick FRI)",
   "type": "heatmap",
   "description": "Time taken to make a request",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(sequencer_client_time_taken_seconds_bucket{type=\"pick_fri\",namespace=~\"$namespace|\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request time(pick SNARK)",
   "type": "heatmap",
   "description": "Time taken to make a request",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(sequencer_client_time_taken_seconds_bucket{type=\"pick_snark\",namespace=~\"$namespace|\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request time(submit FRI)",
   "type": "heatmap",
   "description": "Time taken to make a request",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(sequencer_client_time_taken_seconds_bucket{type=\"submit_fri\",namespace=~\"$namespace|\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request time(submit SNARK)",
   "type": "heatmap",
   "description": "Time taken to make a request",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(sequencer_client_time_taken_seconds_bucket{type=\"submit_snark\",namespace=~\"$namespace|\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}