{
 "title": "EigenDA new dashboard",
 "time": { "from": "2024-09-23T18:15:30.000Z", "to": "2024-09-23T18:35:47.000Z" },
 "panels": [
  { "title": "Eigen DA statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average dispatch latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(server_da_dispatcher_blob_dispatch_latency_seconds_sum{}[$__rate_interval]))/sum(rate(server_da_dispatcher_blob_dispatch_latency_seconds_count{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average inclusion latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(server_da_dispatcher_inclusion_latency_sum{}[$__rate_interval]))/sum(rate(server_da_dispatcher_inclusion_latency_count{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average blob size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(server_da_dispatcher_blob_size_bytes_sum{}[$__rate_interval])) \n/\nsum(rate(server_da_dispatcher_blob_size_bytes_count{}[$__rate_interval]))\n",
     "legendFormat": "Avg blob size"
    }
   ]
  },
  {
   "title": "Blobs pending dispatch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "server_da_dispatcher_blobs_pending_dispatch{}",
     "legendFormat": "pending blobs"
    }
   ]
  },
  {
   "title": "Dispatched & Included blobs",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "server_da_dispatcher_blobs_included{}",
     "legendFormat": "included blobs"
    },
    {
     "expr": "server_da_dispatcher_blobs_dispatched{}",
     "legendFormat": "dispatched blobs"
    }
   ]
  }
 ]
}