{
 "title": "Partners - provers",
 "tags": [ "Era" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(prover_fri_prover_blob_fetch_time_sum,cluster)"
    }
   },
   {
    "name": "circuit_id",
    "query": {
     "query": "label_values(fri_prover_prover_jobs,circuit_id)"
    }
   },
   {
    "name": "witness_generation_round",
    "query": {
     "query": "label_values(server_fri_witness_generator_jobs,round)"
    }
   },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "Prover General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Base layer queued jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(fri_prover_prover_jobs{type=\"queued\", aggregation_round=\"0\"}) by (circuit_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recursive layer queued jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "max(fri_prover_prover_jobs{type=\"queued\", aggregation_round=~\"1|2|3\"}) by (circuit_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L1 Batch height for base layer circuits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max(fri_prover_block_number{aggregation_round=\"0\"}) by (circuit_id)",
     "legendFormat": "circuit_{{circuit_id}}"
    },
    {
     "expr": "max by (stage) (server_block_number{stage=~\"sealed\", namespace=~\"$namespace|\"})",
     "legendFormat": "sealed"
    }
   ]
  },
  {
   "title": "L1 Batch height for recursive layer circuits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "max(fri_prover_block_number{aggregation_round=~\"1|2|3\"}) by (circuit_id, aggregation_round)",
     "legendFormat": "circuit_{{aggregation_round}}_{{circuit_id}}"
    },
    {
     "expr": "max by (stage) (server_block_number{stage=~\"sealed\", namespace=~\"$namespace|\"})",
     "legendFormat": "sealed"
    }
   ]
  },
  {
   "title": "L1 Batch height not sent to prover",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "max(fri_prover_oldest_unpicked_batch)",
     "legendFormat": "unpicked batch"
    },
    {
     "expr": "max(fri_prover_oldest_not_generated_batch)",
     "legendFormat": "not-generated batch"
    },
    {
     "expr": "max by (stage) (server_block_number{stage=~\"sealed\"})",
     "legendFormat": "sealed"
    },
    {
     "expr": "min(fri_prover_oldest_unprocessed_block_by_round) by (aggregation_round)",
     "legendFormat": "unpr_batch_round_{{aggregation_round}}"
    }
   ]
  },
  {
   "title": "Pending prover per group per cluster",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\nsum by (cluster, prover_group_id)\n    (label_replace(\n        label_replace(\n            sum by(cluster, phase, pod) (kube_pod_status_phase{pod=~\"prover-gpu-fri-spec.*\", phase=\"Pending\"}),\n            \"cluster\", \"$1\", \"cluster\", \".*?-(.*)\"\n        ),\n    \"prover_group_id\", \"$1\", \"pod\", \"^prover-gpu-fri-spec-([0-9]+)(-[0-9a-zA-Z-]+)?$\")) > 0",
     "legendFormat": "{{cluster}}: {{prover_group_id}} "
    }
   ]
  },
  {
   "title": "Running prover per group per cluster",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster, prover_group_id)\n    (label_replace(\n        label_replace(\n            sum by(cluster, phase, pod) (kube_pod_status_phase{pod=~\"prover-gpu-fri-spec.*\", phase=\"Running\"}),\n            \"cluster\", \"$1\", \"cluster\", \".*?-(.*)\"\n        ),\n    \"prover_group_id\", \"$1\", \"pod\", \"^prover-gpu-fri-spec-([0-9]+)(-[0-9a-zA-Z-]+)?$\")) > 0",
     "legendFormat": "{{cluster}}: {{prover_group_id}} "
    }
   ]
  },
  {
   "title": "Running prover per cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by (cluster)\n    (label_replace(\n        label_replace(\n            sum by(cluster, phase, pod) (kube_pod_status_phase{pod=~\"prover-gpu-fri-spec.*\", phase=\"Running\"}),\n            \"cluster\", \"$1\", \"cluster\", \".*?-(.*)\"\n        ),\n    \"prover_group_id\", \"$1\", \"pod\", \"^prover-gpu-fri-spec-([0-9]+)(-[0-9a-zA-Z-]+)?$\")) > 0",
     "legendFormat": "{{cluster}}: {{prover_group_id}} "
    }
   ]
  },
  {
   "title": "Proofs per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum by (circuit_type) (rate(prover_fri_prover_gpu_proof_generation_time_count[$__rate_interval]))",
     "legendFormat": "__auto",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Running prover per group per type",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (prover_group_id)\n    (label_replace(\n        label_replace(\n            sum by(phase, pod) (kube_pod_status_phase{pod=~\"prover-gpu-fri-spec.*\", phase=\"Running\"}),\n            \"cluster\", \"$1\", \"cluster\", \".*()?-(.*)\"\n        ),\n    \"prover_group_id\", \"$1\", \"pod\", \"^prover-gpu-fri-spec-([0-9]+)(-[0-9a-zA-Z-]+)?$\")) > 0",
     "legendFormat": "group {{prover_group_id}} "
    }
   ]
  },
  {
   "title": "Basic circuits: Queue Size by id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }
  },
  {
   "title": "Prover Jobs - $circuit_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "repeat": "circuit_id",
   "targets": [
    {
     "expr": "max by (type) (fri_prover_prover_jobs{type=~\"queued|in_progress\", aggregation_round=\"0\", circuit_id=\"$circuit_id\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "GPU Prover performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "GPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "avg_over_time((avg by (prover_group_id) (label_replace(\n  (\n\n      DCGM_FI_DEV_GPU_UTIL\n      * on(pod) group_left(host_ip)\n        sum by (pod, host_ip) (\n          kube_pod_info{pod=~\"dcgm-dcgm-exporter.*\"}\n        )\n    )\n    * on(host_ip) group_left(pod)\n      sum by (pod, host_ip) (\n        sum by (pod) (\n          kube_pod_status_phase{pod=~\"prover-gpu-fri-spec-.*\", phase=\"Running\"}\n        )\n        * on(pod) group_left(host_ip)\n          sum by (pod, host_ip) (\n            kube_pod_info{pod=~\"prover-gpu-fri-spec.*\"}\n          )\n  ),\n  \"prover_group_id\", \"$1\", \"pod\", \"^prover-gpu-fri-spec-([0-9]+)(-[0-9a-zA-Z-]+)?$\"\n)))[15m:])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU utilization by group id and cluster",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "avg_over_time((avg by (cluster, prover_group_id) (label_replace(\n  (\n      DCGM_FI_DEV_GPU_UTIL\n      * on(pod) group_left(host_ip)\n        sum by (pod, host_ip) (\n          kube_pod_info{pod=~\"dcgm-dcgm-exporter.*\"}\n        )\n    )\n    * on(host_ip) group_left(pod)\n      sum by (pod, host_ip) (\n        sum by (pod) (\n          kube_pod_status_phase{pod=~\"prover-gpu-fri-spec-.*\", phase=\"Running\"}\n        )\n        * on(pod) group_left(host_ip)\n          sum by (pod, host_ip) (\n            kube_pod_info{pod=~\"prover-gpu-fri-spec.*\"}\n          )\n      \n  ),\n  \"prover_group_id\", \"$1\", \"pod\", \"^prover-gpu-fri-spec-([0-9]+)(-[0-9a-zA-Z-]+)?$\"\n)))[15m:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU proof average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (circuit_type) ((rate(prover_fri_prover_gpu_proof_generation_time_sum[$__rate_interval])/rate(prover_fri_prover_gpu_proof_generation_time_count[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Witness Vector gens  - sending to prover attempts",
   "type": "heatmap",
   "description": "Histogram - time that state keeper spends waiting for a transaction in mempool. When non-zero - that means that the mempool is empty. When zero - that state keeper is working at highest throughput. The value is capped at one second - if we need to wait more, we start over. That means that if there are no incoming transactions, the graph will show flat line at one second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(rate(prover_fri_witness_vector_generator_prover_attempts_count_bucket[$__rate_interval])) by (le)\n",
     "legendFormat": "{{le}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "GPU proof - percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "histogram_quantile(0.9, sum by (le) (rate(prover_fri_prover_gpu_proof_generation_time_bucket[$__rate_interval])))",
     "legendFormat": "0.9",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "histogram_quantile(0.99, sum by (le) (rate(prover_fri_prover_gpu_proof_generation_time_bucket{namespace=~\"$namespace|\"}[$__rate_interval])))",
     "legendFormat": "0.99",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "histogram_quantile(0.5, sum by (le) (rate(prover_fri_prover_gpu_proof_generation_time_bucket{namespace=~\"$namespace|\"}[$__rate_interval])))",
     "legendFormat": "0.5",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Witness Vector gens  - sending to prover waiting time",
   "type": "heatmap",
   "description": "Histogram - time that state keeper spends waiting for a transaction in mempool. When non-zero - that means that the mempool is empty. When zero - that state keeper is working at highest throughput. The value is capped at one second - if we need to wait more, we start over. That means that if there are no incoming transactions, the graph will show flat line at one second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(rate(prover_fri_witness_vector_generator_prover_waiting_time_bucket[$__rate_interval])) by (le)\n",
     "legendFormat": "{{le}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Assembly generation average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "avg(rate(prover_fri_prover_gpu_assembly_generation_time_sum[$__rate_interval])/rate(prover_fri_prover_gpu_assembly_generation_time_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Witness vector waiting for prover avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (circuit_type, cluster) (rate(prover_fri_witness_vector_generator_prover_waiting_time_sum{circuit_type=~\".*\"}[$__rate_interval])/rate(prover_fri_witness_vector_generator_prover_waiting_time_count{circuit_type=~\".*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Assembly generation - percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "histogram_quantile(0.9, sum by (le) (rate(prover_fri_prover_gpu_assembly_generation_time_bucket[$__rate_interval])))",
     "legendFormat": "0.9",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "histogram_quantile(0.99, sum by (le) (rate(prover_fri_prover_gpu_assembly_generation_time_bucket{namespace=~\"$namespace|\"}[$__rate_interval])))",
     "legendFormat": "0.99",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "histogram_quantile(0.5, sum by (le) (rate(prover_fri_prover_gpu_assembly_generation_time_bucket{namespace=~\"$namespace|\"}[$__rate_interval])))",
     "legendFormat": "0.5",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Witness vector generation average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(prover_fri_witness_vector_generator_gpu_witness_vector_generation_time_sum[$__rate_interval])/rate(prover_fri_witness_vector_generator_gpu_witness_vector_generation_time_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Witness vector - percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "histogram_quantile(0.9, sum by (le) (rate(prover_fri_witness_vector_generator_gpu_witness_vector_generation_time_bucket[$__rate_interval])))",
     "legendFormat": "0.9",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "histogram_quantile(0.99, sum by (le) (rate(prover_fri_witness_vector_generator_gpu_witness_vector_generation_time_bucket{namespace=~\"$namespace|\"}[$__rate_interval])))",
     "legendFormat": "0.99",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "histogram_quantile(0.5, sum by (le) (rate(prover_fri_witness_vector_generator_gpu_witness_vector_generation_time_bucket{namespace=~\"$namespace|\"}[$__rate_interval])))",
     "legendFormat": "0.5",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CPU prover performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prover performance - CPU prove",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 140 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum by (le) (increase(prover_fri_prover_proof_generation_time_bucket[$__interval]))",
       "legendFormat": "{{le}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {}
     ]
    },
    {
     "title": "Prover performance - Setup load time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 140 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum by (le) (increase(prover_fri_prover_setup_data_load_time_bucket[$__interval]))",
       "legendFormat": "{{le}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {}
     ]
    },
    {
     "title": "Prover performance - Blob fetch time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 140 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum by (le) (increase(prover_fri_prover_blob_fetch_time_bucket[$__interval]))",
       "legendFormat": "{{le}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {}
     ]
    },
    {
     "title": "Prover performance - Blob save time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 140 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum by (le) (increase(prover_fri_prover_blob_save_time_bucket[$__interval]))",
       "legendFormat": "{{le}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {}
     ]
    },
    {
     "title": "CPU prove - average",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg(rate(prover_fri_prover_proof_generation_time_sum[$__rate_interval])/rate(prover_fri_prover_proof_generation_time_count[$__rate_interval]))",
       "legendFormat": "Average",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {}
     ]
    },
    {
     "title": "Setup load time - average",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg(rate(prover_fri_prover_setup_data_load_time_sum[$__rate_interval])/rate(prover_fri_prover_setup_data_load_time_count[$__rate_interval]))",
       "legendFormat": "Average",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Blob fetch time - average",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg(rate(prover_fri_prover_blob_fetch_time_sum[$__rate_interval])/rate(prover_fri_prover_blob_fetch_time_count[$__rate_interval]))",
       "legendFormat": "Average",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Blob save time - average",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg(rate(prover_fri_prover_blob_save_time_sum[$__rate_interval])/rate(prover_fri_prover_blob_save_time_count[$__rate_interval]))",
       "legendFormat": "Average",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "CPU prove - percentiles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "histogram_quantile(0.9, sum by (le) (rate(prover_fri_prover_proof_generation_time_bucket{namespace=~\"$namespace|\"}[$__rate_interval])))",
       "legendFormat": "0.9",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "histogram_quantile(0.99, sum by (le) (rate(prover_fri_prover_proof_generation_time_bucket{namespace=~\"$namespace|\"}[$__rate_interval])))",
       "legendFormat": "0.99",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "histogram_quantile(0.5, sum by (le) (rate(prover_fri_prover_proof_generation_time_bucket{namespace=~\"$namespace|\"}[$__rate_interval])))",
       "legendFormat": "0.5",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Setup load - percentiles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "histogram_quantile(0.9, sum by (le) (rate(prover_fri_setup_data_load_time_bucket{namespace=~\"$namespace|\"}[$__rate_interval])))",
       "legendFormat": "0.9",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "histogram_quantile(0.99, sum by (le) (rate(prover_fri_prover_setup_data_load_time_bucket{namespace=~\"$namespace|\"}[$__rate_interval])))",
       "legendFormat": "0.99",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "histogram_quantile(0.5, sum by (le) (rate(prover_fri_prover_setup_data_load_time_bucket{namespace=~\"$namespace|\"}[$__rate_interval])))",
       "legendFormat": "0.5",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Blob fetch - percentiles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "histogram_quantile(0.9, sum by (le) (rate(prover_fri_prover_blob_fetch_time_bucket{namespace=~\"$namespace|\"}[$__rate_interval])))",
       "legendFormat": "0.9",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "histogram_quantile(0.99, sum by (le) (rate(prover_fri_prover_blob_fetch_time_bucket{namespace=~\"$namespace|\"}[$__rate_interval])))",
       "legendFormat": "0.99",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "histogram_quantile(0.5, sum by (le) (rate(prover_fri_prover_blob_fetch_time_bucket{namespace=~\"$namespace|\"}[$__rate_interval])))",
       "legendFormat": "0.5",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Blob save - percentiles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "histogram_quantile(0.9, sum by (le) (rate(prover_fri_prover_blob_save_time_bucket{namespace=~\"$namespace|\"}[$__rate_interval])))",
       "legendFormat": "0.9",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "histogram_quantile(0.99, sum by (le) (rate(prover_fri_prover_blob_save_time_bucket{namespace=~\"$namespace|\"}[$__rate_interval])))",
       "legendFormat": "0.99",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "histogram_quantile(0.5, sum by (le) (rate(prover_fri_prover_blob_save_time_bucket{namespace=~\"$namespace|\"}[$__rate_interval])))",
       "legendFormat": "0.5",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Prover performance - proof verification",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 164 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum by (le) (increase(prover_fri_prover_proof_verification_time_bucket[$__interval]))",
       "legendFormat": "{{le}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {}
     ]
    },
    {
     "title": "proof verification - average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg(rate(prover_fri_prover_proof_verification_time_sum[$__rate_interval])/rate(prover_fri_prover_proof_verification_time_count[$__rate_interval]))",
       "legendFormat": "Average",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Basic Witness Generation Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 },
   "collapsed": true,
   "panels": [
    {
     "title": "Witness generation time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 141 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum by (le) (increase(prover_fri_witness_generator_witness_generation_time_bucket{stage=\"wit_gen_basic_circuits\"}[$__interval]))",
       "legendFormat": "{{le}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Prepare job time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 141 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum by (le) (increase(prover_fri_witness_generation_prepare_job_time_bucket{aggregation_round=\"BasicCircuits\"}[$__interval]))",
       "legendFormat": "{{le}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {}
     ]
    },
    {
     "title": "Blob fetch time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 141 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum by (le) (increase(prover_fri_witness_generator_blob_fetch_time_bucket{stage=\"wit_gen_basic_circuits\"}[$__interval]))",
       "legendFormat": "{{le}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {}
     ]
    },
    {
     "title": "Blob save time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 141 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum by (le) (increase(prover_fri_witness_generator_blob_save_time_bucket{stage=\"wit_gen_basic_circuits\"}[$__interval]))",
       "legendFormat": "{{le}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {}
     ]
    },
    {
     "title": "Witness generation - average",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "(avg by (stage) (rate(prover_fri_witness_generator_witness_generation_time_sum{stage=\"wit_gen_basic_circuits\"}[$__rate_interval])) / avg by (stage) (rate(prover_fri_witness_generator_witness_generation_time_count{stage=\"wit_gen_basic_circuits\"}[$__rate_interval])))",
       "legendFormat": "Average",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {}
     ]
    },
    {
     "title": "Prep job - average",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "(avg by (stage) (rate(prover_fri_witness_generator_prepare_job_time_sum{stage=\"wit_gen_basic_circuits\"}[$__rate_interval])) / avg by (stage) (rate(prover_fri_witness_generator_prepare_job_time_count{stage=\"wit_gen_basic_circuits\"}[$__rate_interval])))",
       "legendFormat": "Average",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {}
     ]
    },
    {
     "title": "Blob fetch - average",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "(avg by (stage) (rate(prover_fri_witness_generator_blob_fetch_time_sum{stage=\"wit_gen_basic_circuits\"}[$__rate_interval])) / avg by (stage) (rate(prover_fri_witness_generator_blob_fetch_time_count{stage=\"wit_gen_basic_circuits\"}[$__rate_interval])))\n",
       "legendFormat": "Average",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {}
     ]
    },
    {
     "title": "Witness generation - average",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "(avg by (stage) (rate(prover_fri_witness_generator_witness_generation_time_sum{stage=\"wit_gen_basic_circuits\"}[$__rate_interval])) / avg by (stage) (rate(prover_fri_witness_generator_witness_generation_time_count{stage=\"wit_gen_basic_circuits\"}[$__rate_interval])))\n",
       "legendFormat": "Average",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {}
     ]
    },
    {
     "title": "Witness generation - percentiles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "histogram_quantile(0.9, sum by (le) (rate(prover_fri_witness_generator_witness_generation_time_bucket{stage=\"wit_gen_basic_circuits\"}[$__rate_interval])))",
       "legendFormat": "0.9",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "histogram_quantile(0.99, sum by (le) (rate(prover_fri_witness_generator_witness_generation_time_bucket{aggregation_round=\"BasicCircuits\", namespace=~\"$namespace|\"}[$__rate_interval])))",
       "legendFormat": "0.99",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      },
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "histogram_quantile(0.5, sum by (le) (rate(prover_fri_witness_generation_witness_generation_time_bucket{aggregation_round=\"BasicCircuits\", namespace=~\"$namespace|\"}[$__rate_interval])))",
       "legendFormat": "0.5",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Witness generation peak memory use",
     "type": "timeseries",
     "description": "Shows the amount of memory currently reserved by the machine running witness generation that uses the most.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_rss{container_name=~\"witness-generator-basic-fri.*\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "Witness Generation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 } },
  {
   "title": "$witness_generation_round Witness Generation ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 141 },
   "repeat": "witness_generation_round",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "max by (type) (server_fri_witness_generator_jobs{round=\"$witness_generation_round\"})",
     "legendFormat": "{{type}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Skipped vs Sampled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
   "targets": [
    {
     "expr": "increase(prover_fri_witness_generator_skipped_blocks[$__rate_interval])",
     "legendFormat": "skipped"
    },
    {
     "expr": "increase(prover_fri_witness_generator_sampled_blocks{pod!=\"$exclude_pod\"}[$__rate_interval])",
     "legendFormat": "sampled"
    }
   ]
  },
  { "title": "Witness vector generation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 157 } },
  {
   "title": "Witness generation time waiting for prover",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 158 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum by (le) (increase(prover_fri_witness_vector_generator_prover_waiting_time_bucket[$__interval]))",
     "legendFormat": "{{le}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Proof Compression (WIP)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 167 } },
  {
   "title": "queued jobs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 168 },
   "targets": [
    {
     "expr": "prover_fri_proof_compressor_jobs{type='queued'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Witness generation time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 174 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum by (le) (increase(prover_fri_witness_generator_witness_generation_time_bucket{stage=\"wit_gen_basic_circuits\"}[$__interval]))",
     "legendFormat": "{{le}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Witness generation - average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 174 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "(avg by (stage) (rate(prover_fri_witness_generator_witness_generation_time_sum{stage=\"wit_gen_basic_circuits\"}[$__rate_interval])) / avg by (stage) (rate(prover_fri_witness_generator_witness_generation_time_count{stage=\"wit_gen_basic_circuits\"}[$__rate_interval])))\n",
     "legendFormat": "Average",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {}
   ]
  },
  {
   "title": "Witness generation - percentiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 174 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "histogram_quantile(0.9, sum by (le) (rate(prover_fri_witness_generation_witness_generation_time_bucket{aggregation_round=\"BasicCircuits\"}[$__rate_interval])))",
     "legendFormat": "0.9",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "histogram_quantile(0.99, sum by (le) (rate(prover_fri_witness_generation_witness_generation_time_bucket{aggregation_round=\"BasicCircuits\", namespace=~\"$namespace|\"}[$__rate_interval])))",
     "legendFormat": "0.99",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "histogram_quantile(0.5, sum by (le) (rate(prover_fri_witness_generation_witness_generation_time_bucket{aggregation_round=\"BasicCircuits\", namespace=~\"$namespace|\"}[$__rate_interval])))",
     "legendFormat": "0.5",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Oldest not compressed L1 batch height",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 174 },
   "targets": [
    {
     "expr": "prover_fri_proof_compressor_oldest_not_compressed_batch",
     "legendFormat": "unpr batch"
    },
    {
     "expr": "max by (stage) (server_block_number{stage=~\"sealed\", namespace=~\"$namespace|\"})",
     "legendFormat": "sealed"
    }
   ]
  },
  { "title": "Job attempts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 183 } },
  {
   "title": "FRI GPU prover attempts",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 184 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum by (le) (increase(job_processor_attempts_bucket{service_name=\"FriGpuProver\"}[$__interval]))",
     "legendFormat": "{{le}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "FRI CPU prover attempts",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 184 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum by (le) (increase(job_processor_attempts_bucket{service_name=\"FriCpuProver\"}[$__interval]))",
     "legendFormat": "{{le}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Proof compressor attempts",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 184 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum by (le) (increase(job_processor_attempts_bucket{service_name=\"ProofCompressor\"}[$__interval]))",
     "legendFormat": "{{le}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "FRI basic witness attempts",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 184 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum by (le) (increase(job_processor_attempts_bucket{service_name=\"fri_basic_circuit_witness_generator\"}[$__interval]))",
     "legendFormat": "{{le}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "FRI leaf witness attempts",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 193 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum by (le) (increase(job_processor_attempts_bucket{service_name=\"fri_leaf_aggregation_witness_generator\"}[$__interval]))",
     "legendFormat": "{{le}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "FRI node witness attempts",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 193 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum by (le) (increase(job_processor_attempts_bucket{service_name=\"fri_node_aggregation_witness_generator\"}[$__interval]))",
     "legendFormat": "{{le}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "FRI scheduler witness attempts",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 193 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum by (le) (increase(job_processor_attempts_bucket{service_name=\"fri_scheduler_witness_generator\"}[$__interval]))",
     "legendFormat": "{{le}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "FRI witness vector generator attempts",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 193 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum by (le) (increase(job_processor_attempts_bucket{service_name=\"WitnessVectorGenerator\"}[$__interval]))",
     "legendFormat": "{{le}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Archivers + Zombie count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 202 } },
  {
   "title": "Prover job archived",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 203 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "max(house_keeper_prover_job_archived)",
     "legendFormat": "job count",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Provers archived",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 203 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(house_keeper_gpu_prover_archived)",
     "legendFormat": "provers archived",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Zombie provers count(dead)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(prover_fri_prover_zombie_prover_instances_count{reason=\"dead\"})",
     "legendFormat": "zombie count",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Zombie provers count(absent)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "prover_fri_prover_zombie_prover_instances_count{reason=\"absent\"}",
     "legendFormat": "zombie count",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  }
 ]
}